export const MOCK_DATA = [
    {
      "Delivery_date": "9/8/2023",
      "Route_name": "Orange - 001",
      "City": "SANTA ANA",
      "State": "California",
      "Zip_code": 92703,
      "Delivery_status": "Delivered",
      "Distribution_location": "Orange County",
      "Shipper": "Sunterra",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 001",
      "City": "NEWPORT BEACH",
      "State": "California",
      "Zip_code": 92662,
      "Delivery_status": "Delivered",
      "Distribution_location": "Orange County",
      "Shipper": "Sunterra",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 013",
      "City": "IRVINE",
      "State": "California",
      "Zip_code": 92602,
      "Delivery_status": "Pending",
      "Distribution_location": "Orange County",
      "Shipper": "Sunterra",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 013",
      "City": "IRVINE",
      "State": "California",
      "Zip_code": 92602,
      "Delivery_status": "Pending",
      "Distribution_location": "Orange County",
      "Shipper": "Sunterra",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/8/2023",
      "Route_name": "Orange - 019",
      "City": "COSTA MESA",
      "State": "California",
      "Zip_code": 92626,
      "Delivery_status": "Delivered",
      "Distribution_location": "Orange County",
      "Shipper": "Sunterra",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/6/2023",
      "Route_name": "Imperial - 001",
      "City": "CALEXICO",
      "State": "California",
      "Zip_code": 92231,
      "Delivery_status": "Delivered",
      "Distribution_location": "Imperial",
      "Shipper": "Sunterra",
      "Delivery_partner": "Lerma Logistics"
    },
    {
      "Delivery_date": "9/6/2023",
      "Route_name": "Imperial - 001",
      "City": "CALEXICO",
      "State": "California",
      "Zip_code": 92231,
      "Delivery_status": "Delivered",
      "Distribution_location": "Imperial",
      "Shipper": "Sunterra",
      "Delivery_partner": "Lerma Logistics"
    },
    {
      "Delivery_date": "9/6/2023",
      "Route_name": "Imperial - 001",
      "City": "CALEXICO",
      "State": "California",
      "Zip_code": 92231,
      "Delivery_status": "Delivered",
      "Distribution_location": "Imperial",
      "Shipper": "Sunterra",
      "Delivery_partner": "Lerma Logistics"
    },
    {
      "Delivery_date": "9/6/2023",
      "Route_name": "Imperial - 001",
      "City": "EL CENTRO",
      "State": "California",
      "Zip_code": 92243,
      "Delivery_status": "Delivered",
      "Distribution_location": "Imperial",
      "Shipper": "Sunterra",
      "Delivery_partner": "Lerma Logistics"
    },
    {
      "Delivery_date": "9/6/2023",
      "Route_name": "Imperial - 001",
      "City": "EL CENTRO",
      "State": "California",
      "Zip_code": 92243,
      "Delivery_status": "Delivered",
      "Distribution_location": "Imperial",
      "Shipper": "Sunterra",
      "Delivery_partner": "Lerma Logistics"
    },
    {
      "Delivery_date": "9/6/2023",
      "Route_name": "Imperial - 001",
      "City": "EL CENTRO",
      "State": "California",
      "Zip_code": 92243,
      "Delivery_status": "Delivered",
      "Distribution_location": "Imperial",
      "Shipper": "Sunterra",
      "Delivery_partner": "Lerma Logistics"
    },
    {
      "Delivery_date": "9/6/2023",
      "Route_name": "Imperial - 001",
      "City": "EL CENTRO",
      "State": "California",
      "Zip_code": 92243,
      "Delivery_status": "Delivered",
      "Distribution_location": "Imperial",
      "Shipper": "Sunterra",
      "Delivery_partner": "Lerma Logistics"
    },
    {
      "Delivery_date": "9/7/2023",
      "Route_name": "Imperial - 001",
      "City": "SEELEY",
      "State": "California",
      "Zip_code": 92273,
      "Delivery_status": "Delivered",
      "Distribution_location": "Imperial",
      "Shipper": "Sunterra",
      "Delivery_partner": "Lerma Logistics"
    },
    {
      "Delivery_date": "9/6/2023",
      "Route_name": "Imperial - 001",
      "City": "EL CENTRO",
      "State": "California",
      "Zip_code": 92243,
      "Delivery_status": "Delivered",
      "Distribution_location": "Imperial",
      "Shipper": "Sunterra",
      "Delivery_partner": "Lerma Logistics"
    },
    {
      "Delivery_date": "9/6/2023",
      "Route_name": "Imperial - 001",
      "City": "EL CENTRO",
      "State": "California",
      "Zip_code": 92243,
      "Delivery_status": "Pending",
      "Distribution_location": "Imperial",
      "Shipper": "Sunterra",
      "Delivery_partner": "Lerma Logistics"
    },
    {
      "Delivery_date": "9/7/2023",
      "Route_name": "Imperial - 001",
      "City": "HOLTVILLE",
      "State": "California",
      "Zip_code": 92250,
      "Delivery_status": "Delivered",
      "Distribution_location": "Imperial",
      "Shipper": "Sunterra",
      "Delivery_partner": "Lerma Logistics"
    },
    {
      "Delivery_date": "9/7/2023",
      "Route_name": "Imperial - 001",
      "City": "IMPERIAL",
      "State": "California",
      "Zip_code": 92251,
      "Delivery_status": "Delivered",
      "Distribution_location": "Imperial",
      "Shipper": "Sunterra",
      "Delivery_partner": "Lerma Logistics"
    },
    {
      "Delivery_date": "9/7/2023",
      "Route_name": "Imperial - 001",
      "City": "BRAWLEY",
      "State": "California",
      "Zip_code": 92227,
      "Delivery_status": "Delivered",
      "Distribution_location": "Imperial",
      "Shipper": "Sunterra",
      "Delivery_partner": "Lerma Logistics"
    },
    {
      "Delivery_date": "9/6/2023",
      "Route_name": "Imperial - 001",
      "City": "EL CENTRO",
      "State": "California",
      "Zip_code": 92243,
      "Delivery_status": "Delivered",
      "Distribution_location": "Imperial",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Lerma Logistics"
    },
    {
      "Delivery_date": "9/7/2023",
      "Route_name": "Imperial - 001",
      "City": "NILAND",
      "State": "California",
      "Zip_code": 92257,
      "Delivery_status": "Delivered",
      "Distribution_location": "Imperial",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Lerma Logistics"
    },
    {
      "Delivery_date": "9/7/2023",
      "Route_name": "Imperial - 001",
      "City": "NILAND",
      "State": "California",
      "Zip_code": 92257,
      "Delivery_status": "Delivered",
      "Distribution_location": "Imperial",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Lerma Logistics"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Pending",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Pending",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Pending",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Pending",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Pending",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Pending",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Pending",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Pending",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Pending",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Delivered",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Delivered",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Delivered",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Delivered",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Delivered",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Delivered",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Delivered",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Delivered",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    },
    {
      "Delivery_date": "9/9/2023",
      "Route_name": "Orange - 014",
      "City": "SAN CLEMENTE",
      "State": "California",
      "Zip_code": 92672,
      "Delivery_status": "Delivered",
      "Distribution_location": "Orange County",
      "Shipper": "Fruit Guys",
      "Delivery_partner": "Delivery Surfers"
    }
  ].map((item) => ({
    delivery_date: item.Delivery_date,
    route_name: item.Route_name,
    city: item.City,
    state: item.State,
    zip_code: item.Zip_code,
    delivery_status: item.Delivery_status,
    distribution_location: item.Distribution_location,
    shipper: item.Shipper,
    delivery_partner: item.Delivery_partner,
  }));